export const SET_TRIPS = "trips/SET_TRIPS";
export const TOGGLE_MODAL = "trips/TOGGLE_MODAL";
export const TOGGLE_APARTAMENT_CHECKBOX = "trips/TOGGLE_APARTAMENT_CHECKBOX";
export const TOGGLE_TRIP_DETAILS_FORM = "trips/TOGGLE_TRIP_DETAILS_FORM";
export const SHOULD_BE_CONNECTED = "trips/SHOULD_BE_CONNECTED";
